/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cinema3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['back-wall'].geometry} material={nodes['back-wall'].material} position={[0, 0, -11]} />
      <mesh geometry={nodes.floor.geometry} material={nodes.floor.material} />
      <mesh geometry={nodes['left-wall'].geometry} material={nodes['left-wall'].material} position={[-11, 0, 0]} />
      <mesh geometry={nodes.Man.geometry} material={nodes.Man.material} position={[1.72, 0, -6.02]} rotation={[-Math.PI, -0.26, -Math.PI]} scale={0.43} />
      <mesh geometry={nodes['right-wall'].geometry} material={nodes['right-wall'].material} position={[11, 0, 0]} />
      <mesh geometry={nodes.scss.geometry} material={nodes.scss.material} position={[10.85, 2.53, -8.23]} rotation={[0, -Math.PI / 2, 0]} scale={2.24} />
      <mesh geometry={nodes.javascript.geometry} material={nodes.javascript.material} position={[10.92, 0.79, -4.9]} rotation={[0, -Math.PI / 2, 0]} scale={1.71} />
      <mesh geometry={nodes.blender.geometry} material={nodes.blender.material} position={[10.78, 4.53, -6.61]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.portal.geometry} material={nodes.portal.material} position={[0, 4, -10.8]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/cinema3.glb')
